### ISSUE TITLE
Server Error w/ Redmine 4.0

### ISSUE THREAD

**Issue by albrechtd** [HugoHasenbein/redmine_preview_inline#3]
I want to migrate a Redmine 3.3.1, including this plugin, to
- Redmine version 4.0.7.stable
- Ruby version 2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
- Rails version 5.2.2.1

but I only see a Redmine error page after installation.  The apache log says
```
[ 2020-09-18 11:37:47.3113 2578/7f2246679700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /usr/share/redmine: An error occurred while starting up the preloader.
  Error ID: 115548de
  Error details saved to: /tmp/passenger-error-NXr0p7.html
  Message from application: undefined method `alias_method_chain' for IssuesHelper:Module
Did you mean?  alias_method (NoMethodError)
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline/patches/issues_helper_patch.rb:31:in `block in included'
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline/patches/issues_helper_patch.rb:27:in `class_eval'
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline/patches/issues_helper_patch.rb:27:in `included'
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline/patches/issues_helper_patch.rb:120:in `include'
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline/patches/issues_helper_patch.rb:120:in `<top (required)>'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/share/redmine/plugins/redmine_preview_inline/lib/redmine_preview_inline.rb:25:in `block in <top (required)>'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:605:in `catch'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:199:in `block in halting'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `each'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:89:in `prepare!'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
  /usr/share/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

Any idea how this issue can be fixed?

**Comment by albrechtd** [comment]
I tried the latest version from master (8ea6ebf) and it fixes the issue.  The plugin now works perfectly with Redmine 4.0.7 from buster backports!

Thanks a lot for your great work!
